services:
    php:
        container_name: ${DOCKER_PROJECT_NAME}_php
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/error_logs:/var/log/php
            - ./docker/php/supervisor/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
        build: ./docker/php
        depends_on:
            - postgres

    nginx:
        container_name: ${DOCKER_PROJECT_NAME}_nginx
        image: nginx:1.19-alpine
        restart: unless-stopped
        volumes:
            - ./docker/nginx/logs:/var/log/nginx
            - ./:/var/www/html
            - ./docker/nginx/common.conf:/etc/nginx/common.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - postgres
        ports:
            - ${DOCKER_NGINX_PORT}:80

    postgres:
        image: postgres:14-alpine
        restart: unless-stopped
        container_name: ${DOCKER_PROJECT_NAME}_postgres
        ports:
            - 127.0.0.1:${DOCKER_DATABASE_PORT}:5432
        volumes:
            - ./docker/postgres/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_DB=${DOCKER_PROJECT_NAME}

    redis:
        image: redis:6.0.10-alpine
        restart: unless-stopped
        ports:
            - "127.0.0.1:2902:6379"
        container_name: ${DOCKER_PROJECT_NAME}_redis
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./docker/redis/data:/data
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
        mem_limit: 1g
